// Code generated by ModelQ using a self defined template fragments

package custom

import (
	"database/sql"
	"encoding/gob"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

type Article struct {
	Id         int64     `json:"id"`
	UserId     int64     `json:"user_id"`
	Title      string    `json:"title"`
	State      int       `json:"state"`
	Content    string    `json:"content"`
	Donation   float64   `json:"donation"`
	CreateTime time.Time `json:"create_time"`
	UpdateTime time.Time `json:"update_time"`
}

func (obj Article) String() string {
	if data, err := json.Marshal(obj); err != nil {
		return fmt.Sprintf("<Article Id=%v>", obj.Id)
	} else {
		return string(data)
	}
}

func init() {
	gob.Register(Article{})
}
