// Code generated by ModelQ using a self defined template fragments

package custom

import (
	"database/sql"
	"encoding/gob"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

type Comment struct {
	UserId     int64     `json:"user_id"`
	ArticleId  int64     `json:"article_id"`
	Content    string    `json:"content"`
	CreateTime time.Time `json:"create_time"`
	UpdateTime time.Time `json:"update_time"`
}

func (obj Comment) String() string {
	if data, err := json.Marshal(obj); err != nil {
		return fmt.Sprintf("<Comment UserId=%v ArticleId=%v>", obj.UserId, obj.ArticleId)
	} else {
		return string(data)
	}
}

func init() {
	gob.Register(Comment{})
}
