// Code generated by ModelQ using a self defined template fragments

package custom

import (
	"database/sql"
	"encoding/gob"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

type User struct {
	Id         int64     `json:"id"`
	Name       string    `json:"name"`
	Password   string    `json:"password"`
	IsMarried  int       `json:"is_married"`
	Age        int       `json:"age"`
	CreateTime time.Time `json:"create_time"`
	UpdateTime time.Time `json:"update_time"`
}

func (obj User) String() string {
	if data, err := json.Marshal(obj); err != nil {
		return fmt.Sprintf("<User Id=%d>", obj.Id)
	} else {
		return string(data)
	}
}

func init() {
	gob.Register(User{})
}
