// Code generated by ModelQ, 2014-12-04 18:43
// article.go contains model for the database table [blog.article]

package models

import (
	"time"
)

type Article struct {
	Id         int64     `json:"id", modelq:"PRI,auto_increment"`
	UserId     int64     `json:"user_id", modelq:"MUL"`
	Title      string    `json:"title"`
	State      int16     `json:"state", modelq:"DEFAULT 0"` // 0: published, 1: draft, 2: hidden
	Content    string    `json:"content"`
	Donation   float64   `json:"donation", modelq:"DEFAULT 0.50"`
	CreateTime time.Time `json:"create_time", modelq:"DEFAULT CURRENT_TIMESTAMP"`
	UpdateTime time.Time `json:"update_time", modelq:"DEFAULT CURRENT_TIMESTAMP,on update CURRENT_TIMESTAMP"`
}

// just to bypass the golang import check
var _ = time.Now
