// Code generated by ModelQ, 2014-12-12 11:22
// article.go contains model for the database table [blog.article]

package models

import (
	"database/sql"
	"github.com/mijia/modelq/gmq"
	"time"
)

type Article struct {
	Id         int64     `json:"id"`
	UserId     int64     `json:"user_id"`
	Title      string    `json:"title"`
	State      int       `json:"state"` // 0: published, 1: draft, 2: hidden
	Content    string    `json:"content"`
	Donation   float64   `json:"donation"`
	CreateTime time.Time `json:"create_time"`
	UpdateTime time.Time `json:"update_time"`
}

// just to bypass the golang import check
var _ = time.Now
var _ sql.DB
var _ gmq.OptionInt
