// Code generated by ModelQ, 2014-12-04 18:43
// user.go contains model for the database table [blog.user]

package models

import (
	"time"
)

type User struct {
	Id         int64     `json:"id", modelq:"PRI,auto_increment"`
	Name       string    `json:"name", modelq:"UNI"`
	Password   string    `json:"password"`
	CreateTime time.Time `json:"create_time", modelq:"DEFAULT CURRENT_TIMESTAMP"`
	UpdateTime time.Time `json:"update_time", modelq:"DEFAULT CURRENT_TIMESTAMP,on update CURRENT_TIMESTAMP"`
}

// just to bypass the golang import check
var _ = time.Now
