// Code generated by ModelQ, 2014-12-11 15:37
// user.go contains model for the database table [blog.user]

package models

import (
	"database/sql"
	"github.com/mijia/modelq/gmq"
	"time"
)

type User struct {
	Id         int64     `json:"id"`
	Name       string    `json:"name"`
	Password   string    `json:"password"`
	IsMarried  int       `json:"is_married"`
	Age        int       `json:"age"`
	CreateTime time.Time `json:"create_time"`
	UpdateTime time.Time `json:"update_time"`
}

// just to bypass the golang import check
var _ = time.Now
var _ sql.DB
var _ gmq.OptionInt
